name = "version-f"
description = "Fortran implementation of Semantic Versioning 2.0.0"
license = "Apache-2.0"
version = "0.4.0"
author = "Minh Dao"
maintainer = "hello@minhdao.de"
copyright = "Copyright 2023-2026, Minh Dao"
homepage = "https://github.com/minhqdao/version-f"
keywords = ["semver", "semantic-versioning", "versioning", "version", "fortran"]

[build]
module-naming = true

[extra.fortitude.check]
ignore = ["S061"]
line-length = 132

[extra.fortitude.check.strings]
quotes = "single"
