name: CI
on: push

jobs:
  fpm-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        toolchain:
          - { compiler: gcc, version: "15" }
          - { compiler: intel, version: "2025.2" }
          - { compiler: intel-classic, version: "2021.12" }
        exclude:
          - os: macos-latest
            toolchain: { compiler: intel, version: "2025.2" }
          - os: macos-latest
            toolchain: { compiler: intel-classic, version: "2021.12" }
          - os: windows-latest
            toolchain: { compiler: intel, version: "2025.2" }
          - os: windows-latest
            toolchain: { compiler: intel-classic, version: "2021.12" }
        include:
          - os: ubuntu-latest
            toolchain: { compiler: nvidia-hpc, version: "26.1" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - uses: fortran-lang/setup-fpm@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: fpm test

  test-msys2:
    strategy:
      matrix:
        include:
          [
            { msystem: mingw64, build_variant: "" },
            { msystem: ucrt64, build_variant: "-ucrt" },
          ]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            mingw-w64${{ matrix.build_variant }}-x86_64-gcc-fortran mingw-w64${{
            matrix.build_variant }}-x86_64-fpm
      - run: fpm test

  make-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        toolchain:
          - { compiler: gcc, version: "15" }
        include:
          - os: ubuntu-latest
            toolchain: { compiler: intel, version: "2025.2" }
          - os: ubuntu-latest
            toolchain: { compiler: intel-classic, version: "2021.12" }
          - os: ubuntu-latest
            toolchain: { compiler: nvidia-hpc, version: "26.1" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - run: ${{ steps.setup-fortran.outputs.fc }} --version
      - run: make test FC=${{ steps.setup-fortran.outputs.fc }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Check formatting
        run: |
          pip install fprettify

          diff=$(fprettify -i 2 -r . -d)

          if [[ $diff ]]; then
            red="\033[0;31m"
            cyan="\033[0;36m"
            reset="\033[0m"
            printf -- "$diff\n"
            printf "${red}The code is not correctly formatted. Please run: ${reset}\n"
            printf "${cyan}fprettify -i 2 -r .${reset}\n"
            exit 1
          fi
