name: CI
on: push

jobs:
  fpm-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - { compiler: gcc, version: 13 }
          - { compiler: intel, version: 2024.1 }
          - { compiler: intel-classic, version: 2021.10 }
          - { compiler: lfortran, version: 0.33.0 }
        exclude:
          - os: macos-latest
            toolchain: { compiler: intel, version: 2024.1 }
          - os: windows-latest
            toolchain: { intel-classic, version: 2021.10 }
        include:
          - os: ubuntu-latest
            toolchain: { compiler: nvidia-hpc, version: 23.11 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - uses: fortran-lang/setup-fpm@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: fpm test

  make-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - { compiler: gcc, version: 13 }
          - { compiler: intel, version: 2023.2 }
          - { compiler: intel-classic, version: 2021.10 }
          - { compiler: nvidia-hpc, version: 23.11 }
        include:
          - os: macos-latest
            toolchain: { compiler: gcc, version: 13 }
          - os: macos-13
            toolchain: { compiler: intel-classic, version: 2021.10 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - run: ${{ steps.setup-fortran.outputs.fc }} --version
      - run: make test FC=${{ steps.setup-fortran.outputs.fc }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Check formatting
        run: |
          pip install fprettify

          diff=$(fprettify -i 2 -r . -d)

          if [[ $diff ]]; then
            red="\033[0;31m"
            cyan="\033[0;36m"
            reset="\033[0m"
            printf -- "$diff\n"
            printf "${red}The code is not correctly formatted. Please run: ${reset}\n"
            printf "${cyan}fprettify -i 2 -r .${reset}\n"
            exit 1
          fi
