name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fortran-lang/setup-fpm@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: fpm test
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run : |
          pip install fprettify
          if [[ $(fprettify -i 2 -r . -d) ]]; then
            echo "The code is not formatted correctly."
            echo "Please run fprettify -i 2 -r ."
            exit 1
          fi
