name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fortran-lang/setup-fpm@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: fpm test
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run : |
          pip install fprettify

          OUT=$(fprettify -i 2 -r . -d)

          if [[ $OUT ]]; then
            RED='\033[0;31m'
            CYAN='\033[0;36m'
            NC='\033[0m'
            printf "$OUT"
            printf "${RED}The code is not formatted correctly. Please run: ${NC}\n"
            printf "${CYAN}fprettify -i 2 -r .${NC}\n"
            exit 1
          fi
