name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  fpm-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - compiler: gfortran
            fpm_flags: "--flag '-Wall -Wextra -fcheck=all -fbacktrace'"
          - compiler: ifx
            fpm_flags: "--flag -warn:all"
          - compiler: ifort
            fpm_flags: "--flag -warn:all"
        exclude:
          - os: macos-latest
            toolchain: { compiler: ifx }
          - os: macos-latest
            toolchain: { compiler: ifort }
        include:
          - os: ubuntu-latest
            toolchain:
              compiler: nvfortran
              fpm_flags: "--flag '-Minform=inform'"
          - os: windows-latest
            toolchain:
              msystem: ucrt64
              fpm_flags: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: minhqdao/setup-fortran@v1
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - uses: fortran-lang/setup-fpm@v10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: fpm test ${{ matrix.toolchain.fpm_flags }}

  make-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - compiler: gfortran
            make_flags: "FFLAGS='-O2 -Wall -Wextra -fcheck=all -fbacktrace'"
          - compiler: ifx
            make_flags: 'FFLAGS="-O2 -warn all"'
          - compiler: ifort
            make_flags: 'FFLAGS="-O2 -warn all"'
          - compiler: lfortran
            make_flags: ""
          - compiler: flang
            make_flags: ""
        exclude:
          - os: macos-latest
            toolchain: { compiler: ifx }
          - os: macos-latest
            toolchain: { compiler: ifort }
        include:
          - os: ubuntu-latest
            toolchain:
              compiler: nvfortran
              make_flags: 'FFLAGS="-O2 -Minform=inform"'
          - os: ubuntu-latest
            toolchain:
              compiler: aocc
              make_flags: ""
          - os: ubuntu-24.04-arm
            toolchain:
              compiler: nvfortran
              make_flags: 'FFLAGS="-O2 -Minform=inform"'
          - os: macos-26-intel
            toolchain:
              compiler: ifort
              make_flags: 'FFLAGS="-O2 -warn all"'
          - os: windows-latest
            toolchain:
              msystem: ucrt64
              make_flags: ""
          - os: windows-11-arm
            toolchain:
              compiler: flang
              make_flags: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: minhqdao/setup-fortran@v1
        id: setup
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - run: echo "${{ steps.setup.outputs.version }}"
      - run: make test ${{ matrix.toolchain.make_flags }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Check formatting
        run: |
          pip install fprettify

          diff=$(fprettify -i 2 -r . -d)

          if [[ $diff ]]; then
            red="\033[0;31m"
            cyan="\033[0;36m"
            reset="\033[0m"
            printf -- "$diff\n"
            printf "${red}The code is not correctly formatted. Please run: ${reset}\n"
            printf "${cyan}fprettify -i 2 -r .${reset}\n"
            exit 1
          fi
