name: CI
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - { compiler: gcc, version: 10 }
          - { compiler: intel-classic, version: "2021.9" }
        include:
          - os: ubuntu-latest
            toolchain: { compiler: intel, version: "2023.1" }
        exclude:
          - os: windows-latest
            toolchain: { compiler: intel-classic, version: "2021.9" }

    steps:
      - uses: actions/checkout@v3
      - uses: fortran-lang/setup-fpm@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: awvwgk/setup-fortran@v1
        id: setup-fortran
        # if: ${{ matrix.os != 'ubuntu-latest' && matrix.toolchain.compiler != 'gcc' }}
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Print Fortran compiler version
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
        run: ${{ env.FC }} --version

      - run: fpm test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check formatting
        run: |
          pip install fprettify

          diff=$(fprettify -i 2 -r . -d)

          if [[ $diff ]]; then
            red="\033[0;31m"
            cyan="\033[0;36m"
            reset="\033[0m"
            printf -- "$diff\n"
            printf "${red}The code is not correctly formatted. Please run: ${reset}\n"
            printf "${cyan}fprettify -i 2 -r .${reset}\n"
            exit 1
          fi
